[programs.localnet]
escrow = "WumKLTcpvB6DkiqqEkQxkmUiYHX6Bpw8cR7YzTxjejD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/glorycode/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
